[profile.default]
src = "src"
out = "out"
libs = ["lib"]
viaIR = true
optimizer = true
optimizer_runs = 200


# Optional: You might also want these settings
solc_version = "0.8.24"
evm_version = "paris"

[profile.remappings]
"@openzeppelin/" = "lib/openzeppelin-contracts/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
